dist: xenial
language: csharp
solution: FlightAnalysis.sln
mono: none
dotnet: 2.2.104
script:
  - dotnet restore
  - dotnet test
  - dotnet build
before_install:
  - openssl aes-256-cbc -K $encrypted_201a62003cd5_key -iv $encrypted_201a62003cd5_iv
  - in deploy.key.enc -out deploy.key -d
after_success:
  - eval "$(ssh-agent -s)"
  - chmod 600 deploy.key
  - ssh-add deploy.key
  - ssh-keyscan dokku.skyhop.org >> ~/.ssh/known_hosts
  - git remote add deploy dokku@dokku.skyhop.org:memeeconomy
  - git config --global push.default simple
  - git push deploy master